//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by notes.rc
//
#define IDR_MAINFRAME                   101
#define IDS_APP_NAME                    102
#define IDR_TRAYMENU                    103
#define IDS_CLOSE                       103
#define IDI_NOTES_SM                    104
#define IDS_DELETE_NOTE_CONFIRM         104
#define IDS_CREATED_FRM                 105
#define IDS_DELETE                      106
#define IDS_SMALL                       106
#define IDS_MEDIUM                      107
#define IDR_NOTEMENU                    108
#define IDS_LARGE                       108
#define IDR_ACCELERATOR1                109
#define IDS_Settings                    109
#define IDS_SETTINGS                    109
#define IDR_EDIT                        110
#define IDS_ROLLUP                      110
#define IDD_DELETENOTECONFIRM           111
#define IDS_UNROLL                      111
#define IDB_CLOSE_BTNS                  112
#define IDS_STRING112                   112
#define IDS_NONE                        112
#define IDS_NO_LABEL                    113
#define IDR_TRAY_NOTE_MENU              114
#define IDR_TRAY_NOTE_MENU1             115
#define IDD_NOTE_SETTING_PAGE           116
#define IDB_UNROLL_BTNS                 119
#define IDB_ROLLUP_BTNS                 120
#define IDD_NEW_LABEL                   121
#define IDI_TRASH_SM                    122
#define IDD_NOTEBOOKS_SETTING_PAGE      122
#define IDD_SYNC_SETTING_PAGE           123
#define IDD_KEYBOARD_SETTING_PAGE       124
#define IDB_NOTE                        124
#define IDB_TRAY_MENU                   124
#define IDICON                          1001
#define IDC_COMBO_NOTE_FONT_SIZE        1002
#define IDC_EDIT_LABEL                  1003
#define IDC_NOTEBOOK_LIST               1004
#define IDC_NOTEBOOK_NEW                1005
#define IDC_NOTEBOOK_PROPS              1006
#define IDC_NOTEBOOK_DEL                1007
#define IDC_EDIT1                       1009
#define IDC_EDIT2                       1010
#define IDC_HOTKEY                      1011
#define IDC_DELETE                      1013
#define IDC_ASSIGN                      1014
#define IDC_LIST1                       1015
#define IDC_NEW_ACCOUNT                 1019
#define IDC_SYNC                        1020
#define IDC_FORGET_PASS                 1021
#define IDC_BUTTON2                     1023
#define IDC_SYNC_NOW                    1023
#define IDC_CHENGE_PASSWORD             1024
#define IDC_CHANGE_PASSWORD             1024
#define IDC_CHECK1                      1025
#define IDC_ENABLE_SHORTCUTS            1025
#define IDC_CLEAR                       1027
#define IDC_LABELS                      1029
#define IDC_FORGOT_PASSWORD             1030
#define ID_POPUP_NEWNOTE                40001
#define ID_POPUP_ABOUT                  40003
#define ID_POPUP_EXIT                   40004
#define ID_NOTES_NEW                    40008
#define ID_POPUP_DELETE                 40010
#define ID_POPUP_CLOSE                  40011
#define ID_DELETE                       40013
#define ID_CLOSE                        40014
#define ID_ALWAYS_ON_TOP                40015
#define ID_POPUP_ALWAYS_ON_TOP          40018
#define ID_NOTEMENU_CLOSEALL            40019
#define ID_NOTEMENU_CLOSEALLBUTTHIS     40020
#define ID_CLOSEALLBUTTHIS              40021
#define ID_CLOSEALL                     40022
#define ID_TRAYMENU_OPTIONS             40023
#define ID_OPTIONS_FONT                 40024
#define ID_NOTEMENU_SAVETOFILE          40025
#define ID_SAVETOFILE                   40026
#define ID_CLIPBRD_COPY                 40027
#define ID_TRAYNOTEMENU_COPYALLTOCLIPBOARD 40033
#define ID_TRAYNOTEMENU_                40034
#define ID_TRAYNOTEMENU_DELETE          40035
#define ID_TNM_DELETE                   40036
#define ID_TNM_COPYALLTOCLIPBOARD       40037
#define ID_TRAYMENU_NEWANDPASTE         40038
#define ID_NEWANDPASTE                  40039
#define ID_POPUP_NEWANDPASTE            40040
#define ID_PASTE                        40041
#define ID_TRAYMENU_UNDELETE            40042
#define ID_TRAYMENU_MORE                40045
#define ID_TRAYNOTEMENU_ID_CANCEL       40046
#define ID_UNDELETE                     40047
#define ID_MORE_HELP                    40048
#define ID_UNDELETE_EMPTY               40052
#define ID_TNM_OPEN_NOTE                40056
#define ID_TNM_CHECK                    40059
#define ID_NOTEMENU_ROLLUP              40060
#define ID_ROLLUP                       40061
#define ID_TRAYNOTEMENU_MARKED          40062
#define ID_TNM_CHECKED_OPEN             40065
#define ID_TNM_CHECKED_DELETE           40066
#define ID_TRAYNOTEMENU_RESTORE         40067
#define ID_TNM_RESTORE                  40068
#define ID_NOTEMENU_RESTORE             40069
#define ID_RESTORE                      40070
#define ID_SETTINGS                     40092
#define ID_TNM_UNCHECK                  40093
#define ID_UNROLL                       40094
#define ID_LABEL_NEWLABEL               40097
#define ID_TRAYNOTEMENU_LABEL           40099
#define ID_LABEL_NEWLABEL40100          40100
#define ID_TNM_NEWLABEL                 40101
#define ID_TNM_NEWLABEL_CHECKED         40102
#define ID_LABEL_NEW                    40103
#define ID_TRAYCHECKEDNOTEMENU_LABELCHECKED 40104
#define ID_DUMMY                        40106
#define ID_TRAYNOTEMENU_DUPLICATE       40107
#define ID_TNM_DUPLICATE                40108
#define ID_NOTEMENU_DUPLICATE           40109
#define ID_DUPLICATE                    40110
#define ID_TRAYNOTEMENU_CHECKALL        40111
#define ID_TNM_CHECKALL                 40112
#define ID_TNM_UNCHECKALL               40113
#define ID_TRAYMENU_NOTEBOOK            40114
#define ID_NOTEBOOK_HOME                40115
#define ID_NOTEBOOK_WORK                40116
#define ID_NOTEBOOK_NEW                 40117
#define ID_NOTEBOOK_PROPERTIES          40118
#define ID_NOTEBOOK_DELETE              40119
#define ID_POPUP_MANAGE                 40120
#define ID_NOTEBOOK_EMPTY               40121
#define ID_MANAGE_NOTEBOOKS             40122
#define ID_TRAYMENU_DOCUMENTS           40123
#define ID_DOCUMENTS_OPENGOOGLEDOCUMENTS 40124
#define ID_DOCUMENTS_REFRESH            40125
#define ID_TRAYNOTEMENU_MOVETONOTEBOOK  40126
#define ID_MOVETONOTEBOOK_              40127
#define ID_TNM_NOBOOKS                  40128
#define ID_TRAYNOTEMENU_MOVETODOCUMENTS 40129
#define ID_TNM_MOVETODOCS               40130
#define ID_TRAYCHECKEDNOTEMENU_COPYCHECKEDTOCLIPBOARD 40131
#define ID_TNM_COPY                     40132
#define ID_MOVETODOCS                   40133
#define ID_NOBOOKS                      40134
#define ID_TRAYMENU_OPENDOCUMENTS       40135
#define ID_TRAYMENU_MOREACTIONS         40136
#define ID_TRAYNOTEMENU_EXPORT          40137
#define ID_TRAYCHECKEDNOTEMENU_EXPORTCHECKED 40138
#define ID_EXPORTCHECKED_GOOGLEDOCUMENT 40139
#define ID_TNM_GOOGLE_EXPORT            40140
#define ID_NOTEMENU_EXPORT              40141
#define ID_POPUP_SETTINGS               40142
#define ID_TRAYNOTEMENU_TEST            40143
#define ID_TEST_TEST                    40144
#define ID_TRAYNOTEMENU_LABEL40145      40145
#define ID_TRAYCHECKEDNOTEMENU_LABEL    40146
#define ID_LABEL_CLEAR                  40147
#define ID_TNM_CLEARLABEL               40148
#define ID_TNM_REMOVE                   40149
#define ID_REMOVE                       40150
#define ID_TRAYNOTEMENU_CANCEL          40151
#define ID_TNM_CANCEL                   40152

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40153
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
